
default:
  script:
    - yarn

image: node:8.11

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
    - npm install -g yarn
    - node --version
    - npm --version
    - yarn --version
    - yarn
    - yarn run build --ignore *service
    - yarn run test --ignore *service

